#!/bin/sh

# List VS Code extensions and write to a file
code --list-extensions > git-hooks/extensions-list.txt

# Add the extensions list file to the commit
git add git-hooks/extensions-list.txt

# Commit changes with a message
git commit -m "Update list of VS Code extensions"

# Proceed with the push
exit 0